name       : xournalpp
version    : 1.0.15
release    : 3
source     :
    - https://github.com/xournalpp/xournalpp/archive/1.0.15.tar.gz : c4d035fe2a356318810f9757e079048935898a75c1ed38a1262eb6a0609d4c54
license    : GPL-2.0-or-later
component  : office.viewers
summary    : Xournal++ is a handwriting notetaking software with PDF annotation support
description: |
    Xournal++ is a hand note taking software written in C++ with the target of flexibility, functionality and speed. Stroke recognizer and other parts are based on Xournal.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libzip)
    - pkgconfig(lua-5.3)
    - pkgconfig(poppler-glib)
    - pkgconfig(portaudiocpp)
    - pkgconfig(sndfile)
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
