name       : xournalpp
version    : 1.1.3
release    : 17
source     :
    - https://github.com/xournalpp/xournalpp/archive/refs/tags/v1.1.3.tar.gz : 5021c7a8f53687edb3a759e079c54d23d5918d83f8d1f5fcd08a1da2ce81bd8b
license    : GPL-2.0-or-later
component  : office.viewers
summary    : Xournal++ is a handwriting notetaking software with PDF annotation support
description: |
    Xournal++ is a hand note taking software written in C++ with the target of flexibility, functionality and speed. Stroke recognizer and other parts are based on Xournal.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libzip)
    - pkgconfig(lua-5.3)
    - pkgconfig(poppler-glib)
    - pkgconfig(portaudiocpp)
    - pkgconfig(sndfile)
setup      : |
    %cmake_ninja
build      : |
    %ninja_build translations
    %ninja_build
install    : |
    %ninja_install
