name       : xournalpp
version    : 1.2.1
release    : 18
source     :
    - https://github.com/xournalpp/xournalpp/archive/refs/tags/v1.2.1.tar.gz : 1f445337d80bbf7ae6a8a5e74975d0a3b84cb546ddcefd7e6448e157801ae9e8
license    : GPL-2.0-or-later
component  : office.viewers
summary    : Xournal++ is a handwriting notetaking software with PDF annotation support
description: |
    Xournal++ is a hand note taking software written in C++ with the target of flexibility, functionality and speed. Stroke recognizer and other parts are based on Xournal.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libzip)
    - pkgconfig(lua-5.3)
    - pkgconfig(poppler-glib)
    - pkgconfig(portaudiocpp)
    - pkgconfig(sndfile)
    - help2man
setup      : |
    %cmake_ninja
build      : |
    %ninja_build translations
    %ninja_build
install    : |
    %ninja_install
